package io.exception.nested_try_block;

public class FinallyBlock01 {
	public static void main(String[] args) {
		
	}
}
